

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: 2022pmds-frontend
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    mode: LEGACYHTML5
    encoding: UTF-8

server:
  port: 9998

#########################################################
#### Actuator
#########################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    caches:
      enabled: false

info:
  organization:
    name: thj0309
  contact:
    email: thj0309@hotmail.com

---

spring:
  config:
    activate:
      on-profile: local

#########################################################
#### Eureka client
#########################################################
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

---

spring:
  config:
    activate:
      on-profile: dev

#########################################################
#### Eureka client
#########################################################
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #defaultZone: ${EUREKA_URL:http://146.56.114.57:8761/eureka/}
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

